version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      electron:
        patterns:
          - electron
          - electron-builder
          - electron-vite
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
